import { Layout } from '@/components/layout/Layout';
import { Link } from 'react-router-dom';
import { 
  Pencil, 
  Settings, 
  Sparkles, 
  Copy,
  ArrowRight,
  CheckCircle2
} from 'lucide-react';
import { Button } from '@/components/ui/button';

const steps = [
  {
    number: '01',
    icon: Pencil,
    title: 'Describe Your Content',
    description: 'Simply type a description of your photo, video, or idea. Be as detailed or brief as you like - our AI understands context.',
    example: '"Sunset beach vacation photo with friends"',
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    number: '02',
    icon: Settings,
    title: 'Choose Your Options',
    description: 'Select your preferred content type (caption, story, post, script) and target platform (Instagram, YouTube, LinkedIn, etc.).',
    example: 'Caption for Instagram',
    color: 'text-accent',
    bgColor: 'bg-accent/10',
  },
  {
    number: '03',
    icon: Sparkles,
    title: 'Generate Content',
    description: 'Click generate and watch as AI creates perfectly crafted, platform-optimized content tailored to your topic.',
    example: 'AI detects "Travel" topic and generates relevant content',
    color: 'text-primary',
    bgColor: 'bg-primary/10',
  },
  {
    number: '04',
    icon: Copy,
    title: 'Copy and Post',
    description: 'Love it? Copy with one click and paste directly to your social media. Want variations? Regenerate instantly.',
    example: 'Ready to publish!',
    color: 'text-accent',
    bgColor: 'bg-accent/10',
  },
];

const benefits = [
  'No sign-up required to try',
  'Instant content generation',
  'Context-aware AI',
  'Platform-optimized output',
  'Unlimited regenerations',
  'Copy with one click',
];

const faqs = [
  {
    question: 'How does the AI understand my content topic?',
    answer: 'Our AI analyzes keywords in your prompt to detect topics like travel, food, fitness, tech, and more. It then generates content specifically tailored to that category, ensuring relevance and engagement.',
  },
  {
    question: 'Can I use the generated content commercially?',
    answer: 'Yes! All content generated by SocialGen AI is yours to use however you like - for personal posts, business accounts, client work, and more.',
  },
  {
    question: 'What makes platform optimization different?',
    answer: 'Each platform has unique characteristics. For example, X (Twitter) content is kept concise, LinkedIn content is more professional, and YouTube descriptions include subscription CTAs.',
  },
  {
    question: 'Can I regenerate if I don\'t like the result?',
    answer: 'Absolutely! Click the Regenerate button as many times as you need until you find the perfect content for your post.',
  },
];

const HowItWorks = () => {
  return (
    <Layout>
      {/* Hero Section */}
      <section className="py-16 sm:py-24 gradient-hero-bg">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <h1 className="text-4xl sm:text-5xl font-bold text-foreground mb-6">
              How{' '}
              <span className="gradient-text">SocialGen AI</span>{' '}
              Works
            </h1>
            <p className="text-lg text-muted-foreground mb-8">
              From idea to engaging content in four simple steps. No learning curve, no complicated setup.
            </p>
          </div>
        </div>
      </section>

      {/* Steps Section */}
      <section className="py-16 sm:py-24 bg-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            {steps.map((step, index) => (
              <div key={index} className="relative">
                {/* Connector Line */}
                {index < steps.length - 1 && (
                  <div className="absolute left-7 top-20 w-0.5 h-24 bg-gradient-to-b from-border to-transparent hidden sm:block" />
                )}
                
                <div className="flex gap-6 mb-12 sm:mb-16">
                  {/* Step Number & Icon */}
                  <div className="shrink-0">
                    <div className={`w-14 h-14 rounded-2xl ${step.bgColor} flex items-center justify-center relative`}>
                      <step.icon className={`w-6 h-6 ${step.color}`} />
                      <span className="absolute -top-2 -right-2 w-6 h-6 rounded-full bg-foreground text-background text-xs font-bold flex items-center justify-center">
                        {step.number}
                      </span>
                    </div>
                  </div>
                  
                  {/* Content */}
                  <div className="flex-1">
                    <h3 className="text-xl font-semibold text-foreground mb-2">
                      {step.title}
                    </h3>
                    <p className="text-muted-foreground mb-4 leading-relaxed">
                      {step.description}
                    </p>
                    <div className="inline-flex items-center gap-2 px-4 py-2 bg-muted rounded-lg">
                      <span className="text-sm text-muted-foreground">Example:</span>
                      <span className="text-sm font-medium text-foreground">{step.example}</span>
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Benefits Section */}
      <section className="py-16 sm:py-24 bg-muted/30">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-4xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl sm:text-4xl font-bold text-foreground mb-4">
                Why Creators Love Us
              </h2>
            </div>

            <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
              {benefits.map((benefit, index) => (
                <div
                  key={index}
                  className="flex items-center gap-3 p-4 bg-card rounded-xl border border-border/50"
                >
                  <CheckCircle2 className="w-5 h-5 text-accent shrink-0" />
                  <span className="font-medium text-foreground">{benefit}</span>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section className="py-16 sm:py-24 bg-background">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto">
            <div className="text-center mb-12">
              <h2 className="text-3xl sm:text-4xl font-bold text-foreground mb-4">
                Frequently Asked Questions
              </h2>
            </div>

            <div className="space-y-6">
              {faqs.map((faq, index) => (
                <div
                  key={index}
                  className="bg-card rounded-xl p-6 border border-border/50"
                >
                  <h3 className="font-semibold text-foreground mb-2">
                    {faq.question}
                  </h3>
                  <p className="text-muted-foreground leading-relaxed">
                    {faq.answer}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-16 sm:py-24 bg-muted/30">
        <div className="container mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <h2 className="text-3xl sm:text-4xl font-bold text-foreground mb-4">
            Ready to Try It Yourself?
          </h2>
          <p className="text-lg text-muted-foreground max-w-xl mx-auto mb-8">
            Experience the power of AI-generated social media content.
          </p>
          <Link to="/">
            <Button size="lg" className="gradient-bg shadow-soft hover:shadow-glow group">
              Start Generating Content
              <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-1 transition-transform" />
            </Button>
          </Link>
        </div>
      </section>
    </Layout>
  );
};

export default HowItWorks;
